name: Build Binaries

on:
  push:
    branches-ignore:
    - nightly
  pull_request:
    branches-ignore:
    - nightly

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_macos_intel:
    runs-on: macos-13
#    defaults:
#      run:
#        working-directory: ./build

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: brew install go

    - name: Build
      run:  bash build.sh

    - name: Create Archive
      run: cd $GITHUB_WORKSPACE && zip -r MutagenMon-intel.zip MutagenMon.app

    - name: Save Archive
      uses: actions/upload-artifact@v4
      with:
        name: MutagenMon-intel
        path: MutagenMon-intel.zip

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        for f in $(find . -name '*.zip'); do
          gh release upload ${{ github.ref_name }} $f
        done
